### ISSUE TITLE
Can I please know how are you getting the data from kontests.net  ? 

### ISSUE THREAD

**Issue by subramanyakrishna** [Dhruv35M/CodingDude#1]
When I sent get request to https://kontests.net/api/v1/all , it is giving 404. Can I please know how are you getting the data for the website?

**Comment by Dhruv35M** [comment]
Yes, you are correct; it's because they stopped API services. I have hosted my backend and am scraping the data to display contest details.

**Comment by subramanyakrishna** [comment]
Thank you
