### ISSUE TITLE
GFG contest link is wrong

### ISSUE THREAD

**Issue by tripathi-abhishek** [Dhruv35M/CodingDude#3]
instead of practice.geeksforgeeks.org, clicking on the contest in the extension, the link goes to geeksforgeeks.org.

example:

https://www.geeksforgeeks.org/contest/gfg-weekly-171-rated-contest/  -> wrong
https://practice.geeksforgeeks.org/contest/gfg-weekly-171-rated-contest -> right

**Comment by Dhruv35M** [comment]
Thanks for reaching me out, I will definitely fix it in next update.
